supi: "imsi-208930000000002"
mcc: "208"
mnc: "93"
key: "8baf473f2f8fd09487cccbd7097c6862"
op: "8e27b6af0e692e750f32667a3b14605d"
opType: "OPC"
amf: "8000"
imei: "356938035643803"
imeiSv: "4370816125816151"
gnbSearchList:
  - 127.0.0.1
  - gnb1.free5gc.org
uacAic:
  mps: false
  mcs: false
uacAcc:
  normalClass: 0
  class11: false
  class12: false
  class13: false
  class14: false
  class15: false
sessions:
  - type: "IPv4"
    apn: "internet"
    slice:
      sst: 0x01
      sd: 0x010203
  - type: "IPv4"
    apn: "internet"
    slice:
      sst: 0x01
      sd: 0x112233
configured-nssai:
  - sst: 0x01
    sd: 0x010203
  - sst: 0x01
    sd: 0x112233
default-nssai:
  - sst: 1
    sd: 1
integrity:
  IA1: true
  IA2: true
  IA3: true
ciphering:
  EA1: true
  EA2: true
  EA3: true
integrityMaxRate:
  uplink: "full"
  downlink: "full"
