mcc: "208"
mnc: "93"
nci: "0x000000010"
idLength: 32
tac: 1
linkIp: 127.0.0.1
ngapIp: gnb3.free5gc.org
gtpIp: gnb3.free5gc.org
amfConfigs:
  - address: amf.free5gc.org
    port: 38412
slices:
  - sst: 0x1
    sd: 0x010203
  - sst: 0x1
    sd: 0x112233
ignoreStreamIds: true
